mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^polls/', include('polls.urls', namespace="polls")),
    url(r'^admin/', include(admin.site.urls)),
]

polls/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^test$', views.test, name='test'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
]

polls/models.py
import datetime
 
from django.db import models
from django.utils import timezone

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def __str__(self):
        return self.question_text
    def was_published_recently(self):
        now = timezone.now() 
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'

class Choice(models.Model):
    question = models.ForeignKey(Question)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text

polls/views.py
from django.shortcuts import get_object_or_404, render, render_to_response
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.views import generic
from django.utils import timezone

from .models import Choice, Question


def test(request):
    latest_question_list = Question.objects.filter(
                             pub_date__lte=timezone.now()
                           ).order_by('-pub_date')[:5]
        
    ctx_dict = {'latest_question_list': latest_question_list }
    return render_to_response('polls/test.html', ctx_dict)


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list' 

    def get_queryset(self):
        """
        Return the last five published questions (not including those
        set to be published in the future).
        """
        return Question.objects.filter(
            pub_date__lte=timezone.now()
        ).order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'

    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())

class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'


def vote(request, question_id):
    p = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = p.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': p,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(p.id,)))

polls/templates/polls/detail.html
<link rel="stylesheet" href="https://storage.googleapis.com/code.getmdl.io/1.0.0/material.indigo-deep_orange.min.css">
<script src="https://storage.googleapis.com/code.getmdl.io/1.0.0/material.min.js"></script>
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">

<style>
  .quiz-card.mdl-card {
    top: 20px;
    margin: auto;
    background: #3E4EB8;
  }
  .quiz-card > .mdl-card__actions {
    border-color: rgba(255, 255, 255, 0.2);
  }
  .quiz-card > .mdl-card__title,
  .quiz-card > .mdl-card__actions > .mdl-button {
    color: #fff;
  }
  .quiz-card * {
      display: block;
  }
</style>

<div class="mdl-layout mdl-js-layout mdl-layout--fixed-drawer mdl-layout--overlay-drawer-button">
  <header class="mdl-layout__header">
    <div class="mdl-layout__header-row">
      <span class="mdl-layout-title"/>
    </div>
  </header>
  <div class="mdl-layout__drawer">
    <span class="mdl-layout-title">Demo Quiz App</span>
    <nav class="mdl-navigation">
         <a class="mdl-navigation__link" href="{% url 'polls:index' %}">Home</a>
    </nav>
  </div>
  <main class="mdl-layout__content">
    <form action="{% url 'polls:vote' question.id %}" method="post">
      <div class="mdl-card mdl-shadow--2dp quiz-card">
        <div class="mdl-card__title mdl-card--expand">
        <h3>{{ question.question_text }}</h3>

        {% csrf_token %}
        {% for choice in question.choice_set.all %}
        <label class="mdl-radio mdl-js-radio mdl-js-ripple-effect" for="choice{{ forloop.counter }}">
          <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" class="mdl-radio__button"/>
          <span class="mdl-radio__label">{{ choice.choice_text }}</span>
        </label>
        {% endfor %}
        </div>
        <div class="mdl-card__actions mdl-card--border">
          <input type="submit" value="Vote" class="mdl-button mdl-js-button mdl-button--colored mdl-js-ripple-effect" />
        </div>
      </div>
    </form>
    {% if error_message %}<br/><p style="text-align: center;"><strong>{{ error_message }}</strong></p>{% endif %}
  </main>
</div>

polls/templates/polls/index.html
<link rel="stylesheet" href="https://storage.googleapis.com/code.getmdl.io/1.0.0/material.indigo-deep_orange.min.css">
<script src="https://storage.googleapis.com/code.getmdl.io/1.0.0/material.min.js"></script>
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">

{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />

{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
         <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}            

polls/templates/polls/results.html
<link rel="stylesheet" href="https://storage.googleapis.com/code.getmdl.io/1.0.0/material.indigo-deep_orange.min.css">
<script src="https://storage.googleapis.com/code.getmdl.io/1.0.0/material.min.js"></script>
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">

<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>